name: SonarQube Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_HOST_URL: http://your-sonarqube-server:9000
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
